### ISSUE TITLE
account_check_printing_report_base yields and error when trying to apply payment to multiple invoices 

### ISSUE THREAD

**Issue by andres-pcg** [OCA/account-payment#205]
i have summited a pull request with a fix for this issue, but it needs some re-factoring 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 936, in _call_
    return self.method(*args, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/addons/account/models/account_payment.py", line 235, in create_payments
    payments.post()
  File "/odoo/odoo-server/src/custom/iterativo/dominicana-premium/invoice_payment_method/models/account_payment.py", line 44, in post
    res = super(AccountPayment, self).post()
  File "/odoo/odoo-server/src/custom/oca/account-payment/account_check_printing_report_base/models/account_payment.py", line 40, in post
    if (self.journal_id.check_print_auto and
  File "/odoo/odoo-server/src/odoo/odoo/fields.py", line 935, in _get_
    record.ensure_one()
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 4366, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.payment(1613, 1614)

**Comment by pedrobaeza** [comment]
Don't open a new issue if you have the PR #203 opened.
