### ISSUE TITLE
[11.0] account_check_printing_base Bug at printing of check report

### ISSUE THREAD

**Issue by mamcode** [OCA/account-payment#230]
At moment of print check of a payment raise the following error:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_630_917
  File "<template>", line 2, in body_call_content_916
  File "<template>", line 5, in foreach_915
  File "<template>", line 27, in foreach_914
KeyError: 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/OCB-11.0/addons/web/controllers/main.py", line 1620, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/.repo_requirements/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-11.0/addons/web/controllers/main.py", line 1569, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_actions_report.py", line 637, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_actions_report.py", line 675, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_actions_report.py", line 479, in render_template
    return view_obj.render_template(template, values)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1211, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/odoo/OCB-11.0/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1220, in render
    return self.env[engine].render(self.id, qcontext)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 272, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 350, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: 4
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_630_917
  File "<template>", line 2, in body_call_content_916
  File "<template>", line 5, in foreach_915
  File "<template>", line 27, in foreach_914
KeyError: 4

Error to render compiling AST
KeyError: 4
Template: 630
Path: /templates/t/t/div[2]/t/div/div/div[2]/div/t/table/tbody/t
Node: <t t-foreach="paid_lines[o.id]" t-as="line">
                                            <tr style="text-align:left;border-top: 0px;">
                                                <td style="padding-top:3mm;">
                                                    <span t-esc="line['date_due']"/>
                                                </td>
                                                <td>
                                                    <span t-esc="line['reference'] or line['number']"/>
                                                </td>
                                                <td>
                                                    <span t-esc="line['amount_total']" t-esc-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: &quot;o.currency_id&quot;}"/>
                                                </td>
                                                <td>
                                                    <span t-esc="line['residual']" t-esc-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: &quot;o.currency_id&quot;}"/>
                                                </td>
                                                <td>
                                                    <span t-esc="line['paid_amount']" t-esc-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: &quot;o.currency_id&quot;}"/>
                                                </td>
                                            </tr>
                                        </t>

**Steps to reproduce the error:**
1. Go to a runbot instance of OCA (account-payment).
2. Go to the vendor bill BILL/2019/0002
3. Register a payment for this invoice, in wizard form press the button "validate".

**Tested in runbot instance** http://3359094-11-0-8a268a.runbot3.odoo-community.org

I think that error is in method get_report_values in this line https://github.com/OCA/account-payment/blob/8a268aae5d46d006a53dc813600722b60a40df42/account_check_printing_report_base/report/check_print.py#L99 because the method get_paid_lines is being called without active_model='account.payment' in context. 
Is really necesary this condition https://github.com/OCA/account-payment/blob/8a268aae5d46d006a53dc813600722b60a40df42/account_check_printing_report_base/report/check_print.py#L23 in method get_paid_lines ?

**Comment by edwinvedder** [comment]
Trying help.. Check dependencies in __manifest.py__.   Add "account", restart odoo.
Please, send comments.

**Comment by Swapnesh-SerpentCS** [comment]
Fixed in https://github.com/OCA/account-payment/pull/267 at https://github.com/OCA/account-payment/pull/267/commits/c97223507009e5f9c6399bc1cb80516eea5ace5a

**Comment by Swapnesh-SerpentCS** [comment]
Hello @mamcode, 
Could you please update the source code and test this again ?
Its seems to be working file on old Instances as well.

Thanks

**Comment by mamcode** [comment]
Hello @Swapnesh-SerpentCS ok thank you, give me a chance and I'll try in the next few hours.

**Comment by mamcode** [comment]
@Swapnesh-SerpentCS Sorry for my late reply, the error no longer appears, I tried it on runbot.
