### ISSUE TITLE
[account_check_print_report_base] expected singleton error when priting check for internal transfers

### ISSUE THREAD

**Issue by andres-pcg** [OCA/account-payment#294]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/models.py", line 4414, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/addons/web/controllers/main.py", line 1620, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/opt/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1569, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo/odoo/addons/base/ir/ir_actions_report.py", line 640, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/mnt/extra-addons/odoo/enterprise/web_studio/models/report.py", line 17, in render_qweb_html
    return super(Report, self).render_qweb_html(docids, data)
  File "/opt/odoo/odoo/addons/base/ir/ir_actions_report.py", line 670, in render_qweb_html
    data = report_model.get_report_values(docids, data=data)
  File "/mnt/extra-addons/iterativo/iterativo-premium/l10n_do_check_print/report/check_print.py", line 12, in get_report_values
    return super(ReportCheckPrint, self).get_report_values(docids, data)
  File "/mnt/extra-addons/oca/account-payment/account_check_printing_report_base/report/check_print.py", line 96, in get_report_values
    paid_lines = self.get_paid_lines(objects)
  File "/mnt/extra-addons/oca/account-payment/account_check_printing_report_base/report/check_print.py", line 73, in get_paid_lines
    amls = rec_lines.matched_credit_ids.mapped('credit_move_id') + \
  File "/opt/odoo/odoo/fields.py", line 946, in __get__
    record.ensure_one()
  File "/opt/odoo/odoo/models.py", line 4417, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.move.line(85391, 85388)

**Comment by andres-pcg** [comment]
Line 73 of account-payment/account_check_printing_report_base/report/check_print.py; is trying to access matched_credit_ids function when rec_lines on **internal transfers** comes with multiple records. 
```
amls = rec_lines.matched_credit_ids.mapped('credit_move_id') + \
                rec_lines.matched_debit_ids.mapped('debit_move_id')
```

**Comment by andres-pcg** [comment]
@jbeficent

**Comment by andres-pcg** [comment]
@pedrobaeza can we fix this by accesing the first record by adding index to **rec_lines** Like this:

```amls = rec_lines[0].matched_credit_ids.mapped('credit_move_id') + \
                rec_lines[0].matched_debit_ids.mapped('debit_move_id')```

I have a couple of customers complaining about this issue.

**Comment by andres-pcg** [comment]
@mreficent this issue started after commit 8a82165

**Comment by MiquelRForgeFlow** [comment]
Solved by https://github.com/OCA/account-payment/pull/295. This issue can be closed.

**Comment by andres-pcg** [comment]
thank you very much @mreficent
